spring:
  application:
    name: barber-shop-api
  datasource:
    url: jdbc:postgresql://localhost:5432/dioava
    username: miguelpg
    password: 32412294
  jpa:
    hibernate:
      ddl-auto: validate